---
- name: get current user
  command: whoami
  register: current_user
  changed_when: current_user.rc != 0
  check_mode: no
  tags:
    - tmux

- name: add tmux config for current user
  copy:
    src: "{{ item }}"
    dest: "/home/{{ current_user.stdout }}/{{ item }}"
    owner: "{{ current_user.stdout }}"
    group: "{{ current_user.stdout }}"
    mode: 0640
  with_items:
    - .tmux.conf
  when:
    - not current_user.stdout | search('root')
  tags:
    - tmux

- name: check if ruby is installed
  command: ruby -v
  register: ruby
  changed_when: ruby.rc != 0
  check_mode: no
  ignore_errors: yes
  tags:
    - tmux

- block:
    - name: install tmuxinator for current user
      gem:
        name: "{{ item }}"
        state: latest
      with_items:
        - tmuxinator

    - name: ensure tmuxinator directory exist for current user
      file:
        path: "/home/{{ current_user.stdout }}/{{ item }}"
        state: directory
        owner: "{{ current_user.stdout }}"
        group: "{{ current_user.stdout }}"
        mode: 0700
      with_items:
        - .tmuxinator

    - name: add tmuxinator profiles
      copy:
        src: ".tmuxinator/{{ item }}"
        dest: "/home/{{ current_user.stdout }}/.tmuxinator/{{ item }}"
        owner: "{{ current_user.stdout }}"
        group: "{{ current_user.stdout }}"
        mode: 0640
      with_items:
        - default.yml
  when:
    - not current_user.stdout | search('root')
    - ruby.rc == 0
  tags:
    - tmux
