---
language: python

python: "2.7"

env:
  - ANSIBLE_VERSION=1.9.2

install:
  # Install Ansible.
  - pip install ansible==$ANSIBLE_VERSION

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i inventory test.yml --syntax-check
  # TODO: once travis-ci includes an option to use CentOS, run the playbook for real.

notifications:
  irc:
    channels:
      - "chat.freenode.net##phatypus"
