---
- name: get current user
  command: whoami
  register: current_user
  become: no
  changed_when: current_user.rc != 0
  check_mode: no
  tags:
    - shell

# skeleton
- name: ensure directories exist for skel
  file:
    path: "/etc/skel/{{ item }}"
    state: directory
    mode: 0700
  with_items:
    - .bin
    - .ssh
    - tmp
  tags:
    - shell

- name: add ssh config for skel
  copy:
    src: ".ssh/{{ item }}"
    dest: "/etc/skel/.ssh/{{ item }}"
    mode: 0600
  with_items:
    - config
  tags:
    - shell

- name: add custom scripts for skel
  copy:
    src: ".bin/{{ item }}"
    dest: /etc/skel/.bin/
    mode: 0700
  with_items:
    - diff-highlight
  tags:
    - shell

- name: add dotfiles for skel
  copy:
    src: "{{ item }}"
    dest: "/etc/skel/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - .aliases
    - .bash_profile
    - .bash_prompt
    - .bashrc
    - .exports
    - .functions
    - .gitconfig
    - .gitignore_global
    - .gitmessage
    - .inputrc
    - .path
    - .tmux.conf
    - .wgetrc
  tags:
    - shell

# root
- name: ensure directories exist for root
  file:
    path: "/root/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0700
  with_items:
    - .ssh
    - tmp
  tags:
    - shell

- name: add ssh config for root
  copy:
    src: ".ssh/{{ item }}"
    dest: "/root/.ssh/{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - config
  tags:
    - shell

- name: add dotfiles for root
  copy:
    src: "{{item }}"
    dest: "/root/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - .aliases
    - .bash_profile
    - .bash_prompt
    - .bashrc
    - .exports
    - .functions
    - .inputrc
    - .path
    - .tmux.conf
    - .wgetrc
  tags:
    - shell

# current user
- name: ensure directories exist for current user
  file:
    path: "/home/{{ current_user.stdout }}/{{ item }}"
    state: directory
    owner: "{{ current_user.stdout }}"
    group: "{{ current_user.stdout }}"
    mode: 0700
  with_items:
    - .bin
    - .ssh
    - tmp
  tags:
    - shell

- name: add ssh config for current user
  copy:
    src: ".ssh/{{ item }}"
    dest: "/home/{{ current_user.stdout }}/.ssh/{{ item }}"
    owner: "{{ current_user.stdout }}"
    group: "{{ current_user.stdout }}"
    mode: 0600
  with_items:
    - config
  when:
    - not current_user.stdout | search('root')
  tags:
    - shell

- name: add custom scripts for current user
  copy:
    src: ".bin/{{ item }}"
    dest: "/home/{{ current_user.stdout }}/.bin/{{ item }}"
    owner: "{{ current_user.stdout }}"
    group: "{{ current_user.stdout }}"
    mode: 0700
  with_items:
    - diff-highlight
  when:
    - not current_user.stdout | search('root')
  tags:
    - shell

- name: add dotfiles for current user
  copy:
    src: "{{ item }}"
    dest: "/home/{{ current_user.stdout }}/{{ item }}"
    owner: "{{ current_user.stdout }}"
    group: "{{ current_user.stdout }}"
    mode: 0644
  with_items:
    - .aliases
    - .bash_profile
    - .bash_prompt
    - .bashrc
    - .exports
    - .functions
    - .gitconfig
    - .gitignore_global
    - .gitmessage
    - .inputrc
    - .path
    - .tmux.conf
    - .wgetrc
  when:
    - not current_user.stdout | search('root')
  tags:
    - shell
