---
- name: install core yum packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
    disablerepo: "*"
    enablerepo: "base,extras,updates"
  with_items:
    - epel-release
    - yum-plugin-fastestmirror
    - yum-utils
  tags:
    - yum

- name: install common packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ v_yum_common_packages }}"
  tags:
    - yum
