---
- name: enable selinux
  selinux: policy=targeted state={{ v_selinux_state }}
  tags:
    - selinux

- name: install selinux related packages
  yum: name={{ item }} state=present
  with_items:
    - "{{ v_selinux_yum_packages }}"
  tags:
    - selinux
    - yum

- name: check if selinux is enabled
  command: getenforce
  register: sestatus
  changed_when: sestatus.rc != 0
  tags:
    - selinux

- name: add additional ports to a selinux type
  shell: "semanage port -m -t {{ item.type }} -p {{ item.protocol }} {{ item.port }}"
  when: (sestatus.stdout.find('Enforcing') != -1) and (item.type is defined and item.protocol is defined and item.port is defined)
  with_items:
    - "{{ v_selinux_ports }}"
  ignore_errors: yes
  tags:
    - selinux
