---
# skeleton
- name: configure bash for skel
  copy:
    src: "{{ item }}"
    dest: "/etc/skel/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - .aliases
    - .bash_profile
    - .bash_prompt
    - .bashrc
    - .exports
    - .functions
    - .gitconfig
    - .gitignore_global
    - .gitmessage
    - .inputrc
    - .path
    - .tmux.conf
    - .wgetrc
  tags:
    - bash

# root
- name: configure bash for root
  copy:
    src: "{{item }}"
    dest: "/root/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - .aliases
    - .bash_profile
    - .bash_prompt
    - .bashrc
    - .exports
    - .functions
    - .inputrc
    - .path
    - .tmux.conf
    - .wgetrc
  tags:
    - bash

# current user
- name: get current user
  command: whoami
  register: current_user
  become: no
  changed_when: current_user.rc != 0
  check_mode: no
  tags:
    - bash

- name: configure bash for current user
  copy:
    src: "{{ item }}"
    dest: "/home/{{ current_user.stdout }}/{{ item }}"
    owner: "{{ current_user.stdout }}"
    group: "{{ current_user.stdout }}"
    mode: 0644
  with_items:
    - .aliases
    - .bash_profile
    - .bash_prompt
    - .bashrc
    - .exports
    - .functions
    - .gitconfig
    - .gitignore_global
    - .gitmessage
    - .inputrc
    - .path
    - .tmux.conf
    - .wgetrc
  when:
    - current_user.stdout.find('root') == -1
  tags:
    - bash
