---
- name: create groups
  group: name={{ item }}
    state=present
  with_items:
    - "{{ v_groups }}"
  tags:
    - users
    - groups

- name: create users
  user: name={{ item.username }}
    groups={{ item.groups if item.groups is defined else "" }}
    shell=/bin/bash
    password={{ item.password if item.password is defined else "!" }}
  with_items:
    - "{{ v_private_users }}"
  when: item.username is defined
  tags:
    - users

- name: add pub keys for users
  authorized_key: user={{ item.username }}
    key="{{ lookup('file', item.key) }}"
  with_items:
    - "{{ v_private_users }}"
  when: item.key is defined
  tags:
    - users
    - keys

- name: get current user
  shell: whoami
  sudo: no
  register: current_user
  changed_when: current_user.rc != 0
  tags:
    - users

- name: delete users
  user: name={{ item.username }}
    state=absent
  with_items:
    - "{{ v_private_users_delete }}"
  when: (item.username is defined) and (current_user.stdout.find('{{ item.username }}') == -1)
  tags:
    - users
