---
- name: clean yum cache
  command: yum clean all
  args:
    warn: no
  tags:
    - yum
    - update

- name: update packages to the latest version
  yum:
    name: "*"
    state: latest
    update_cache: yes
  tags:
    - yum
    - update
