---
- name: log martian packets
  sysctl:
    name: net.ipv4.conf.all.log_martians
    value: 1
    state: present
    sysctl_set: yes
  tags:
    - sysctl

- name: ignore ICMPv4 bogus error responses
  sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: 1
    state: present
    sysctl_set: yes
  tags:
    - sysctl

- name: do not respond to ICMPv4 sent to the broadcast address
  sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: 1
    state: present
    sysctl_set: yes
  tags:
    - sysctl

- name: enable TCP syncookies
  sysctl:
    name: net.ipv4.tcp_syncookies
    value: 1
    state: present
    sysctl_set: yes
  tags:
    - sysctl

- name: enable virtual address space randomization
  sysctl:
    name: kernel.randomize_va_space
    value: 2
    state: present
    sysctl_set: yes
  tags:
    - sysctl

- name: do not accept ICMPv4 redirect packets on any interface
  sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: 0
    state: present
    sysctl_set: yes
  tags:
    - sysctl

- name: disable sending ICMPv4 redirects
  sysctl:
    name: net.ipv4.conf.default.send_redirects
    value: 0
    state: present
    sysctl_set: yes
  tags:
    - sysctl

- name: disable sending ICMPv4 redirects on all interfaces
  sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: 0
    state: present
    sysctl_set: yes
  tags:
    - sysctl

- name: disable IPv6
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present
    sysctl_set: yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
  tags:
    - sysctl
