---
- name: install yum-cron
  yum: name=yum-cron state=present update_cache=yes
  tags:
    - yum-cron

- name: configure yum-cron
  template: src={{ item }}
    dest=/etc/yum/{{ item | basename | regex_replace('\.j2','') }}
    backup=yes
    owner=0 group=0 mode=0644
  with_fileglob:
    - ../templates/*.j2
  notify:
    - restart yum-cron
  tags:
    - yum-cron
